### ISSUE TITLE
Different resistor

### ISSUE THREAD

**Issue by swiezaks** [Geocali/18650_tester#9]
is it possible to use diffrent resistor ? in my local electronic shop do not have 4R/5W  only have 4R3/5W,will the indications be very different?  need to change the resistor value in the program?

**Comment by Geocali** [comment]
Hello !

Yes it is fine, you just need to change the R variable in battery_tester/tester.py

If you don't change it, you will have some error ((4,3-4)/4*100 = 7.5%) on the values of the voltage and capacity
